import '@/modules/profile/rules/ItMustBeValidPhoneFromTheCountrySpain'
import '@/modules/profile/rules/TheNameMustContainOnlyLettersWithAccentsAndWithoutAccentsRule'
import '@/modules/profile/rules/MustBeAPasswordSecure'
import '@/modules/profile/rules/ConfirmPassword'
import '@/modules/profile/rules/FormRulesUpdateDataUser'
import '@/modules/students/rules/DniMustBeFromSpain'
import '@/modules/resources/rules/ImageQuestionRequiredValid'
import '@/modules/resources/rules/questions'
