import '@/modules/profile/rules/ItMustBeValidPhoneFromTheCountrySpain'
import '@/modules/profile/rules/TheNameMustContainOnlyLettersWithAccentsAndWithoutAccentsRule'
import '@/modules/profile/rules/MustBeAPasswordSecure'
import '@/modules/profile/rules/ConfirmPassword'
import '@/modules/students/rules/DniMustBeFromSpain'
