name: Deploy API
on:
  push:
    tags:
      - '*' # Everything that doesnt include  '/' character

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      SERVER: ${{ vars.PRODUCTION_SERVER }}
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      SSH_USER: ${{ secrets.SSH_USER }}
      SSH_PORT: ${{ secrets.SSH_PORT }}
      VUE_APP_SECRET_KEY_DESCRYPT_TOKEN: ${{ secrets.VUE_APP_SECRET_KEY_DESCRYPT_TOKEN }}
      FOLDER_NAME: ${{ vars.FOLDER_NAME || '/var/www/academy750-frontend' }}
      VUE_APP_BASE_URL_API_PRODUCTION: 'https://entrenamiento.academia750.es'

    steps:
      # This is not really working need to debug
      # - name: Only Main branch
      #   if: endsWith(github.ref, 'main') == false
      #   run: exit -1

      - name: 🚚 Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install dependencies
        run: npm ci

      - name: Prepare env
        run: |
          cp .env.example .env

      - name: Build Vue project
        run: npm run build

      - name: Deploy to Production
        uses: easingthemes/ssh-deploy@v2.2.4
        with:
          SSH_PRIVATE_KEY: ${{ env.SSH_PRIVATE_KEY }}
          REMOTE_HOST: ${{ env.SERVER }}
          REMOTE_USER: ${{ env.SSH_USER || 'ubuntu' }}
          REMOTE_PORT: ${{ env.SSH_PORT || 22 }}
          SOURCE: './dist'
          TARGET: ${{ env.FOLDER_NAME }}
          ARGS: '-rltgoDzvO --delete'
          EXCLUDE: '.env'
